package edu.lk.ijse.projectgym.demo76promax.bo;

public enum BOTypes {

    ADDCOACH,
//    ADDCLEANER,
//    ADDITEMS,
//    ADDSUPLAYERS,
    CUSTORMERDEATILESMENU,
   CUSTORMERMANEGE,
    CUSTORMERDORPAYMENTS,
//    DASHBORD,
//    DELETECLENER,
//    DELETECOACH,
//    EDITEOTOJENARETMASSEGE,
//    EMPLOYEEATENDENS,
//    EMPLOYEEDATAFROMATABLE,
//    EMPLOYEEPAYMENTS,
//    EMPLOYEEPAGEDEATILES,
//    EMPLOYEEPAGE,
//    INVENTORYPAGE,
//    LOGINFORSYSTEM,
//    LOGINMANEGER,
//    LOGIMNOWNER,
//    MANEGEEXSAIS,
//    MANEGERLOGIN,
//    MONTHLYMASSEGESENDPAGE,
//    MONTHLYRIPORTPAGE,
//    ODERPAGE,
//    OWNERANDADMINLOGINPAGE,
//    SENDMASSEGEPAGE,
//    SENDSHEDULTOCUSTORMER,
    USERDEATILESPAGE,
    USERDORPASWORD,
    USERMANEGE


}
