package edu.lk.ijse.projectgym.demo76promax.bo;

public enum BOTypes {

    SAVECOACH,
    SAVECLEANER,
//    ADDITEMS,
    ADDSUPLAYERS,
    CUSTORMERDEATILESMENU,
   CUSTORMERMANEGE,
    CUSTORMERDORPAYMENTS,
//    DASHBORD,
    DELETECLENER,
    DELETECOACH,
    EDITEOTOJENARETMASSEGE,
//    EMPLOYEEATENDENS,
    EMPLOYEEDATAFROMATABLE,
    EMPLOYEEPAYMENTS,
//    EMPLOYEEPAGEDEATILES,
    EMPLOYEEMANEGEFIRSTPAGE,
//    INVENTORYPAGE,
//    LOGINFORSYSTEM,
//    LOGINMANEGER,
//    LOGIMNOWNER,
    MANEGEEXSAIS,
//    MANEGERLOGIN,
//    MONTHLYMASSEGESENDPAGE,
//    MONTHLYRIPORTPAGE,
    PLACEODER,
//    OWNERANDADMINLOGINPAGE,
//    SENDMASSEGEPAGE,
    SENDSHEDULTOCUSTORMER,
    USERDEATILESPAGE,
    USERDORPASWORD,
    USERMANEGE,
    ITEM


}
